enable-experiment:
  - extension-methods

linter:

  rules:
    always_use_package_imports: true
    avoid_print: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_multiple_declarations_per_line: true
    avoid_relative_lib_imports: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    cancel_subscriptions: true
    collection_methods_unrelated_type: true
    deprecated_consistency: true
    hash_and_equals: true
    literal_only_boolean_expressions: true
    null_check_on_nullable_type_parameter: true
    no_duplicate_case_values: true
    no_runtimeType_toString: true
    require_trailing_commas: true
    sort_constructors_first: true
    use_colored_box: true
    use_decorated_box: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    missing_whitespace_between_adjacent_strings: true
    file_names: true
    annotate_overrides: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_return_types_on_setters: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    directives_ordering: true
    prefer_single_quotes: true
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule