name: medace_app
description: MedAce App Powered by Master Lms Study

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.5+67

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #networking
  http: ^0.13.4
  dio: ^5.2.1+1

  #stateManagement
  flutter_bloc: ^8.1.3

  #utils
  meta: ^1.1.6
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  share_plus: ^6.3.1
  package_info_plus: ^3.1.2
  device_info_plus: ^8.1.0
  overlay_support: ^2.1.0
  intl: ^0.17.0


  #googleSignIn
  google_sign_in: ^6.0.2

  #facebookSignIn
  flutter_facebook_auth: ^5.0.7

  #utils
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  webview_flutter: ^4.2.1
  webview_cookie_manager: ^2.0.6
  webview_flutter_wkwebview: ^3.0.4
  webview_flutter_android: ^3.9.3
  flutter_inappwebview: ^5.7.2+3
  connectivity_plus: ^3.0.3
  external_path: ^1.0.1
  logger: ^1.3.0

  #video_players
  vimeo_video_player: ^0.0.10
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  chewie: ^1.5.0

  #firebase
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4

  #ui
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  shimmer: 2.0.0
  image_picker: ^0.8.4+11
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_html: 3.0.0-alpha.6
  file_picker: ^5.2.5
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  html_unescape: ^2.0.0
  page_transition: ^2.0.9
  in_app_purchase: ^3.0.8
  image: ^4.1.7
  fluttertoast: ^8.2.1

  #VDO
  vdocipher_flutter: ^2.6.5
  #Rename
  rename_app: ^1.3.2
  #change package_rename
  change_app_package_name: ^1.1.0
  #change icon
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/localization/default_locale.json
